/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IERC721 } from "./IERC721";
export type { ISynthetixProxy } from "./ISynthetixProxy";
