name = "synthetix-periphery"
description = "Synthetix system supplemental contracts"

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"


[setting.erc20_version]
defaultValue = "0.4.0"

[setting.synthetix_version]
defaultValue = "1.0.0"

[setting.chainlink_version]
defaultValue = "0.9-mock"

[setting.lusd_price]
defaultValue = "1000000000000000000"

[setting.snx_price]
defaultValue = "10000000000000000000"

[setting.weth_price]
defaultValue = "1000000000000000000000"

[import.lusd]
source = "erc20:<%= settings.erc20_version %>"
options.name = "Liquity USD"
options.symbol = "LSUD"

[import.snx]
source = "erc20:<%= settings.erc20_version %>"
options.name = "Synthetix Token"
options.symbol = "SNX"

[import.aggregator_snx]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "snx"
options.rate = "<%= settings.snx_rate %>"

[import.aggregator_lusd]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "lusd"
options.rate = "<%= settings.lusd_rate %>"

[import.aggregator_weth]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "weth"
options.rate = "<%= settings.weth_rate %>"

[import.synthetix]
source = "synthetix-main:<%= settings.synthetix_version %>"
options.owner = "<%= settings.owner %>"

[contract.Multicall]
artifact = "Multicall3"
step = 1

[contract.Onboarding]
artifact = "Onboarding"
step = 1

[contract.WETH]
artifact = "WETH9"
step = 1

[invoke.register_lusd_collateral]
on = ["synthetix.Proxy"]
fromCall.func = "owner"
func = "adjustCollateralType"
args = [
    "<%= imports.lusd.contracts.token.address %>",
    "<%= imports.aggregator_lusd.contracts.aggregator.address %>",
    "1500000000000000000",
    "1100000000000000000",
    true
]
step = 2

[invoke.register_snx_collateral]
on = ["synthetix.Proxy"]
fromCall.func = "owner"
func = "adjustCollateralType"
args = [
    "<%= imports.snx.contracts.token.address %>",
    "<%= imports.aggregator_snx.contracts.aggregator.address %>",
    "4000000000000000000",
    "2000000000000000000",
    true
]
step = 2

[invoke.register_weth_collateral]
on = ["synthetix.Proxy"]
fromCall.func = "owner"
func = "adjustCollateralType"
args = [
    "<%= contracts.WETH.address %>",
    "<%= imports.aggregator_weth.contracts.aggregator.address %>",
    "3000000000000000000",
    "1500000000000000000",
    true
]
step = 2
