/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as opengsn from "./@opengsn";
import type * as contracts from "./contracts";
import type * as interfaces from "./interfaces";

export type { opengsn };

export type { contracts };

export type { interfaces };
export * as factories from "./factories";
export type { BaseRelayRecipient } from "./@opengsn/contracts/src/BaseRelayRecipient";
export { BaseRelayRecipient__factory } from "./factories/@opengsn/contracts/src/BaseRelayRecipient__factory";
export type { IRelayRecipient } from "./@opengsn/contracts/src/interfaces/IRelayRecipient";
export { IRelayRecipient__factory } from "./factories/@opengsn/contracts/src/interfaces/IRelayRecipient__factory";
export type { Multicall3 } from "./contracts/Multicall3";
export { Multicall3__factory } from "./factories/contracts/Multicall3__factory";
export type { Onboarding } from "./contracts/Onboarding";
export { Onboarding__factory } from "./factories/contracts/Onboarding__factory";
export type { WETH9 } from "./contracts/WETH9";
export { WETH9__factory } from "./factories/contracts/WETH9__factory";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
export type { IERC721 } from "./interfaces/IERC721";
export { IERC721__factory } from "./factories/interfaces/IERC721__factory";
export type { ISynthetixProxy } from "./interfaces/ISynthetixProxy";
export { ISynthetixProxy__factory } from "./factories/interfaces/ISynthetixProxy__factory";
